name: tests


on:
  push:

jobs:

  run-tests:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - "3.7"
  
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run-tests
        run: pytest . -s --durations 0

      - uses: codecov/codecov-action@v3
